name: tasklist
description: "A new Flutter project."
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0

  # USE ESTAS VERSÕES EXATAS (Série Estável 2.x e 4.x)
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: 4.17.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true